# Generated by Django 5.2.1 on 2025-05-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('OPERATOR', 'Оператор'), ('EVALUATOR', 'Оценщик')], max_length=10),
        ),
    ]
