# Generated by Django 5.2.1 on 2025-05-28 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rug_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество ковров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Ожидает забор', 'Ожидает забор'), ('Оценка', 'Оценка'), ('Чистка', 'Чистка'), ('Готов к возврату', 'Готов к возврату'), ('Доставлен клиенту', 'Доставлен клиенту'), ('Завершён', 'Завершён'), ('Отменён', 'Отменён'), ('Ошибка', 'Ошибка в данных / требует уточнения')], default='Новый', max_length=50),
        ),
    ]
