# Generated by Django 5.2.1 on 2025-05-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_rug_count_alter_order_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rug',
            name='size',
        ),
        migrations.AddField(
            model_name='rug',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rug',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rug',
            name='condition_before',
            field=models.TextField(blank=True),
        ),
    ]
